// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bleulace.mgt.presentation;

import java.util.List;

privileged aspect BundleDTO_Roo_JavaBean {
    
    public List<TaskDTO> BundleDTO.getTasks() {
        return this.tasks;
    }
    
    public void BundleDTO.setTasks(List<TaskDTO> tasks) {
        this.tasks = tasks;
    }
    
}
