// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bleulace.domain.feed.event;

import com.bleulace.domain.feed.event.FeedUpdatedEvent;

privileged aspect FeedUpdatedEvent_Roo_JavaBean {
    
    public String FeedUpdatedEvent.getId() {
        return this.id;
    }
    
}
