// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bleulace.domain.management.model;

import com.bleulace.domain.management.model.Task;

privileged aspect Task_Roo_JavaBean {
    
    public boolean Task.isComplete() {
        return this.complete;
    }
    
    public void Task.setComplete(boolean complete) {
        this.complete = complete;
    }
    
}
