function net_bluelace_ui_BluelaceWidgetSet(){var Z='',W=' top: -1000px;',ub='" for "gwt:onLoadErrorFn"',sb='" for "gwt:onPropertyErrorFn"',db='");',vb='#',Nb='.cache.js',xb='/',Db='//',Kb='2E31110F121765BBFD40414F5F193146',Mb=':',Lb=':1',mb='::',Tb=':moduleBase',Y='<!doctype html>',$='<html><head><\/head><body><\/body><\/html>',pb='=',wb='?',rb='Bad handler "',X='CSS1Compat',bb='Chrome',ab='DOMContentLoaded',R='DUMMY',Sb='__gwtDevModeHook:net.bluelace.ui.BluelaceWidgetSet',Fb='android 2.',Gb='android2',Cb='base',Ab='baseUrl',M='begin',S='body',L='bootstrap',zb='clear.cache.gif',ob='content',Pb='end',cb='eval("',Rb='file:',N='gwt.codesvr.net.bluelace.ui.BluelaceWidgetSet=',O='gwt.codesvr=',tb='gwt:onLoadErrorFn',qb='gwt:onPropertyErrorFn',nb='gwt:property',ib='head',Qb='http:',T='iframe',yb='img',fb='javascript',U='javascript:""',Ob='loadExternalRefs',jb='meta',hb='moduleRequested',gb='moduleStartup',kb='name',P='net.bluelace.ui.BluelaceWidgetSet',Jb='net.bluelace.ui.BluelaceWidgetSet.devmode.js',Bb='net.bluelace.ui.BluelaceWidgetSet.nocache.js',lb='net.bluelace.ui.BluelaceWidgetSet::',V='position:absolute; width:0; height:0; border:none; left: -1000px;',eb='script',Ib='selectingPermutation',Q='startup',Hb='std',_='undefined',Eb='webkitvariant';var o=window;var p=document;r(L,M);function q(){var a=o.location.search;return a.indexOf(N)!=-1||a.indexOf(O)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:P,sessionId:o.__gwtStatsSessionId,subSystem:Q,evtGroup:a,millis:(new Date).getTime(),type:b})}}
net_bluelace_ui_BluelaceWidgetSet.__sendStats=r;net_bluelace_ui_BluelaceWidgetSet.__moduleName=P;net_bluelace_ui_BluelaceWidgetSet.__errFn=null;net_bluelace_ui_BluelaceWidgetSet.__moduleBase=R;net_bluelace_ui_BluelaceWidgetSet.__softPermutationId=0;net_bluelace_ui_BluelaceWidgetSet.__computePropValue=null;net_bluelace_ui_BluelaceWidgetSet.__getPropMap=null;net_bluelace_ui_BluelaceWidgetSet.__gwtInstallCode=function(){};net_bluelace_ui_BluelaceWidgetSet.__gwtStartLoadingFragment=function(){return null};var s=function(){return false};var t=function(){return null};__propertyErrorFunction=null;var u=o.__gwt_activeModules=o.__gwt_activeModules||{};u[P]={moduleName:P};var v;function w(){y();return v}
function x(){y();return v.getElementsByTagName(S)[0]}
function y(){if(v){return}var a=p.createElement(T);a.src=U;a.id=P;a.style.cssText=V+W;a.tabIndex=-1;p.body.appendChild(a);v=a.contentDocument;if(!v){v=a.contentWindow.document}v.open();var b=document.compatMode==X?Y:Z;v.write(b+$);v.close()}
function z(k){function l(a){function b(){if(typeof p.readyState==_){return typeof p.body!=_&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(ab,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(ab,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=x();var f=w();var g;if(navigator.userAgent.indexOf(bb)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(cb));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode(db));g=f.createElement(eb);g.language=fb;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(eb);g.language=fb;g.text=c[i];e.appendChild(g);d(e,g)}}}
net_bluelace_ui_BluelaceWidgetSet.onScriptDownloaded=function(a){l(function(){m(a)})};r(gb,hb);var n=p.createElement(eb);n.src=k;p.getElementsByTagName(ib)[0].appendChild(n)}
net_bluelace_ui_BluelaceWidgetSet.__startLoadingFragment=function(a){return C(a)};net_bluelace_ui_BluelaceWidgetSet.__installRunAsyncCode=function(a){var b=x();var c=w().createElement(eb);c.language=fb;c.text=a;b.appendChild(c);b.removeChild(c)};function A(){var c={};var d;var e;var f=p.getElementsByTagName(jb);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(kb),k;if(j){j=j.replace(lb,Z);if(j.indexOf(mb)>=0){continue}if(j==nb){k=i.getAttribute(ob);if(k){var l,m=k.indexOf(pb);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=Z}c[j]=l}}else if(j==qb){k=i.getAttribute(ob);if(k){try{d=eval(k)}catch(a){alert(rb+k+sb)}}}else if(j==tb){k=i.getAttribute(ob);if(k){try{e=eval(k)}catch(a){alert(rb+k+ub)}}}}}t=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;net_bluelace_ui_BluelaceWidgetSet.__errFn=e}
function B(){function e(a){var b=a.lastIndexOf(vb);if(b==-1){b=a.length}var c=a.indexOf(wb);if(c==-1){c=a.length}var d=a.lastIndexOf(xb,Math.min(c,b));return d>=0?a.substring(0,d+1):Z}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(yb);b.src=a+zb;a=e(b.src)}return a}
function g(){var a=t(Ab);if(a!=null){return a}return Z}
function h(){var a=p.getElementsByTagName(eb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(Bb)!=-1){return e(a[b].src)}}return Z}
function i(){var a=p.getElementsByTagName(Cb);if(a.length>0){return a[a.length-1].href}return Z}
function j(){var a=p.location;return a.href==a.protocol+Db+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==Z){k=h()}if(k==Z){k=i()}if(k==Z&&j()){k=e(p.location.href)}k=f(k);return k}
function C(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return net_bluelace_ui_BluelaceWidgetSet.__moduleBase+a}
function D(){var f=[];var g;function h(a,b){var c=f;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
j[Eb]=function(){{var a=window.navigator.userAgent.toLowerCase();if(a.indexOf(Fb)!=-1){return Gb}return Hb}};i[Eb]={android2:0,std:1};s=function(a,b){return b in i[a]};net_bluelace_ui_BluelaceWidgetSet.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};net_bluelace_ui_BluelaceWidgetSet.__computePropValue=k;o.__gwt_activeModules[P].bindings=net_bluelace_ui_BluelaceWidgetSet.__getPropMap;r(L,Ib);if(q()){return C(Jb)}var l;try{h([Gb],Kb);h([Hb],Kb+Lb);l=f[k(Eb)];var m=l.indexOf(Mb);if(m!=-1){g=parseInt(l.substring(m+1),10);l=l.substring(0,m)}}catch(a){}net_bluelace_ui_BluelaceWidgetSet.__softPermutationId=g;return C(l+Nb)}
function E(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}r(Ob,M);r(Ob,Pb)}
A();net_bluelace_ui_BluelaceWidgetSet.__moduleBase=B();u[P].moduleBase=net_bluelace_ui_BluelaceWidgetSet.__moduleBase;var F=D();if(o){var G=!!(o.location.protocol==Qb||o.location.protocol==Rb);o.__gwt_activeModules[P].canRedirect=G;if(G){var H=Sb;var I=o.sessionStorage[H];if(I&&!o[H]){o[H]=true;o[H+Tb]=B();var J=p.createElement(eb);J.src=I;var K=p.getElementsByTagName(ib)[0];K.insertBefore(J,K.firstElementChild||K.children[0]);return false}}}E();r(L,Pb);z(F);return true}
net_bluelace_ui_BluelaceWidgetSet.succeeded=net_bluelace_ui_BluelaceWidgetSet();