// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bleulace.web.demo.timebox;

import com.bleulace.web.demo.timebox.ParticipantBean;
import java.io.Serializable;

privileged aspect ParticipantBean_Roo_Serializable {
    
    declare parents: ParticipantBean implements Serializable;
    
    private static final long ParticipantBean.serialVersionUID = 1L;
    
}
