package com.bleulace.ui.web.front;

import java.util.LinkedList;
import java.util.List;

import com.bleulace.cqrs.command.CommandGatewayAware;
import com.bleulace.utils.ctx.SpringApplicationContext;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.event.ShortcutAction.KeyCode;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Notification;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;

public class LoginBar extends CustomComponent implements CommandGatewayAware
{

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * 
	 */
	private static final long serialVersionUID = -6490804781048686952L;

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button forgotPassword;
	@AutoGenerated
	private CheckBox rememberMe;
	@AutoGenerated
	private Button submit;
	@AutoGenerated
	private PasswordField password;
	@AutoGenerated
	private TextField username;

	private List<LoginBarListener> listeners = new LinkedList<LoginBarListener>();

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public LoginBar()
	{
		buildMainLayout();
		setCompositionRoot(mainLayout);
		submit.addClickListener(new Button.ClickListener()
		{
			private static final long serialVersionUID = 1L;

			@Override
			public void buttonClick(ClickEvent event)
			{
				setEnabled(false);
				for (LoginBarListener l : listeners)
				{
					l.onLogin(username.getValue(), password.getValue(),
							rememberMe.getValue());
				}
				setEnabled(true);
			}
		});
		submit.setClickShortcut(KeyCode.ENTER);

		forgotPassword.addClickListener(new Button.ClickListener()
		{
			private static final long serialVersionUID = 1L;

			@Override
			public void buttonClick(ClickEvent event)
			{
				Notification.show("NOT YET IMPLEMENTED");
			}
		});
		addListener(SpringApplicationContext.getBean(LoginBarController.class));
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout()
	{
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// username
		username = new TextField();
		username.setCaption("Username");
		username.setImmediate(false);
		username.setWidth("-1px");
		username.setHeight("-1px");
		username.setRequired(true);
		mainLayout.addComponent(username);

		// password
		password = new PasswordField();
		password.setCaption("Password");
		password.setImmediate(false);
		password.setWidth("-1px");
		password.setHeight("-1px");
		password.setRequired(true);
		mainLayout.addComponent(password, "top:0.0px;left:180.0px;");

		// submit
		submit = new Button();
		submit.setCaption("Login");
		submit.setImmediate(true);
		submit.setWidth("-1px");
		submit.setHeight("-1px");
		mainLayout.addComponent(submit, "top:0.0px;left:360.0px;");

		// rememberMe
		rememberMe = new CheckBox();
		rememberMe.setCaption("Remember Me");
		rememberMe.setImmediate(false);
		rememberMe.setWidth("-1px");
		rememberMe.setHeight("-1px");
		mainLayout.addComponent(rememberMe, "top:26.0px;left:0.0px;");

		// forgotPassword
		forgotPassword = new Button();
		forgotPassword.setStyleName("link");
		forgotPassword.setCaption("Forgot your password?");
		forgotPassword.setImmediate(false);
		forgotPassword.setWidth("-1px");
		forgotPassword.setHeight("-1px");
		mainLayout.addComponent(forgotPassword, "top:26.0px;left:180.0px;");

		return mainLayout;
	}

	void addListener(LoginBarListener listener)
	{
		listeners.add(listener);
	}

	interface LoginBarListener
	{
		void onLogin(String username, String password, Boolean rememberMe);
	}
}