// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bleulace.crm.domain.event;


privileged aspect GroupJoinedEvent_Roo_JavaBean {
    
    public String GroupJoinedEvent.getAccountId() {
        return this.accountId;
    }
    
    public void GroupJoinedEvent.setAccountId(String accountId) {
        this.accountId = accountId;
    }
    
}
