// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bleulace.crm.domain.event;


privileged aspect GroupJoinedFeedPayload_Roo_JavaBean {
    
    public String GroupJoinedFeedPayload.getId() {
        return this.id;
    }
    
    public void GroupJoinedFeedPayload.setId(String id) {
        this.id = id;
    }
    
    public String GroupJoinedFeedPayload.getTitle() {
        return this.title;
    }
    
    public void GroupJoinedFeedPayload.setTitle(String title) {
        this.title = title;
    }
    
}
