// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bleulace.domain.crm.model;

import java.util.Date;

privileged aspect FriendRequest_Roo_JavaBean {
    
    public Account FriendRequest.getRequestor() {
        return this.requestor;
    }
    
    public Date FriendRequest.getDateSent() {
        return this.dateSent;
    }
    
}
