// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bleulace.domain.crm.model;

import com.bleulace.domain.crm.model.HashedPassword;

privileged aspect HashedPassword_Roo_JavaBean {
    
    public byte[] HashedPassword.getHash() {
        return this.hash;
    }
    
    public byte[] HashedPassword.getSalt() {
        return this.salt;
    }
    
}
