// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bleulace.domain.management.command;


privileged aspect CancelEventCommand_Roo_JavaBean {
    
    public String CancelEventCommand.getId() {
        return this.id;
    }
    
}
