// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bleulace.domain.management.command;

import com.bleulace.domain.management.command.CreateBundleCommand;

privileged aspect CreateBundleCommand_Roo_JavaBean {
    
    public String CreateBundleCommand.getId() {
        return this.id;
    }
    
}
