// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bleulace.domain.management.command;

import com.bleulace.domain.management.command.CreateTaskCommand;

privileged aspect CreateTaskCommand_Roo_JavaBean {
    
    public String CreateTaskCommand.getId() {
        return this.id;
    }
    
}
