// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bleulace.domain.management.command;


privileged aspect MarkTaskCommand_Roo_JavaBean {
    
    public String MarkTaskCommand.getId() {
        return this.id;
    }
    
    public boolean MarkTaskCommand.isComplete() {
        return this.complete;
    }
    
}
