// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bleulace.domain.management.command;

import com.bleulace.domain.management.command.RsvpCommand;

privileged aspect RsvpCommand_Roo_JavaBean {
    
    public boolean RsvpCommand.isAccepted() {
        return this.accepted;
    }
    
}
