// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bleulace.mgt.application.command;

import com.bleulace.mgt.application.command.MarkResourceCompleteCommand;

privileged aspect MarkResourceCompleteCommand_Roo_JavaBean {
    
    public String MarkResourceCompleteCommand.getId() {
        return this.id;
    }
    
}
