// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bleulace.domain.feed.presentation;

import com.bleulace.domain.feed.presentation.DefaultFeedText;

privileged aspect DefaultFeedText_Roo_JavaBean {
    
    public String DefaultFeedText.getValue() {
        return this.value;
    }
    
}
