// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bleulace.domain.feed.presentation;

import java.util.List;

privileged aspect FeedDTOValue_Roo_JavaBean {
    
    public List<FeedText> FeedDTOValue.getContent() {
        return this.content;
    }
    
}
