// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bleulace.domain.feed.presentation;


privileged aspect HyperlinkedFeedText_Roo_JavaBean {
    
    public String HyperlinkedFeedText.getNavState() {
        return this.navState;
    }
    
}
