// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bleulace.domain.crm.command;


privileged aspect CommentCommand_Roo_JavaBean {
    
    public String CommentCommand.getContent() {
        return this.content;
    }
    
    public void CommentCommand.setContent(String content) {
        this.content = content;
    }
    
}
