// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bleulace.mgt.domain.event;

import com.bleulace.utils.jpa.DateWindow;

privileged aspect EventRescheduledEvent_Roo_JavaBean {
    
    public DateWindow EventRescheduledEvent.getWindow() {
        return this.window;
    }
    
}
