// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bleulace.crm.application.command;


privileged aspect ChangePasswordCommand_Roo_JavaBean {
    
    public String ChangePasswordCommand.getValue() {
        return this.value;
    }
    
    public void ChangePasswordCommand.setValue(String value) {
        this.value = value;
    }
    
}
