// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bleulace.crm.application.command;


privileged aspect JoinGroupCommand_Roo_JavaBean {
    
    public String JoinGroupCommand.getGroupId() {
        return this.groupId;
    }
    
    public String JoinGroupCommand.getAccountId() {
        return this.accountId;
    }
    
}
