// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bleulace.crm.application.command;


privileged aspect ReplyToFriendRequestCommand_Roo_JavaBean {
    
    public boolean ReplyToFriendRequestCommand.isAccept() {
        return this.accept;
    }
    
    public void ReplyToFriendRequestCommand.setAccept(boolean accept) {
        this.accept = accept;
    }
    
}
