// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bleulace.crm.application.command;


privileged aspect SendFriendRequestCommand_Roo_JavaBean {
    
    public String SendFriendRequestCommand.getInitiatorId() {
        return this.initiatorId;
    }
    
    public String SendFriendRequestCommand.getRecipientId() {
        return this.recipientId;
    }
    
}
