// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bleulace.crm.application.event;


privileged aspect AccountLoginAttemptedEvent_Roo_JavaBean {
    
    public Boolean AccountLoginAttemptedEvent.getSuccess() {
        return this.success;
    }
    
}
