// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bleulace.crm.application.event;


privileged aspect GroupCreatedEvent_Roo_JavaBean {
    
    public String GroupCreatedEvent.getTitle() {
        return this.title;
    }
    
    public void GroupCreatedEvent.setTitle(String title) {
        this.title = title;
    }
    
}
