// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bleulace.crm.application.event;

import com.bleulace.crm.application.event.LoginAttemptedEvent;

privileged aspect LoginAttemptedEvent_Roo_JavaBean {
    
    public Boolean LoginAttemptedEvent.getSuccess() {
        return this.success;
    }
    
}
