// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bleulace.mgt.domain;

import com.bleulace.mgt.domain.AbstractProject;

privileged aspect AbstractProject_Roo_JavaBean {
    
    public String AbstractProject.getTitle() {
        return this.title;
    }
    
    public void AbstractProject.setTitle(String title) {
        this.title = title;
    }
    
}
