// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bleulace.mgt.domain;


privileged aspect Bundle_Roo_JavaBean {
    
    public Project Bundle.getProject() {
        return this.project;
    }
    
}
