// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.bluelace.domain.account;

import net.bluelace.domain.account.AccountRegistrationPayload;
import org.joda.time.LocalDate;

privileged aspect AccountRegistrationPayload_Roo_JavaBean {
    
    public String AccountRegistrationPayload.getFirstName() {
        return this.firstName;
    }
    
    public void AccountRegistrationPayload.setFirstName(String firstName) {
        this.firstName = firstName;
    }
    
    public String AccountRegistrationPayload.getLastName() {
        return this.lastName;
    }
    
    public void AccountRegistrationPayload.setLastName(String lastName) {
        this.lastName = lastName;
    }
    
    public String AccountRegistrationPayload.getEmail() {
        return this.email;
    }
    
    public void AccountRegistrationPayload.setEmail(String email) {
        this.email = email;
    }
    
    public String AccountRegistrationPayload.getPhone() {
        return this.phone;
    }
    
    public void AccountRegistrationPayload.setPhone(String phone) {
        this.phone = phone;
    }
    
    public LocalDate AccountRegistrationPayload.getBirthday() {
        return this.birthday;
    }
    
    public void AccountRegistrationPayload.setBirthday(LocalDate birthday) {
        this.birthday = birthday;
    }
    
}
