// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bleulace.domain.management.event;


privileged aspect EventCanceledEvent_Roo_JavaBean {
    
    public String EventCanceledEvent.getId() {
        return this.id;
    }
    
}
